# Generated by Django 5.2.5 on 2025-08-17 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_carinventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='bio',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
